<?php

/**
 * @file
 * Contains demomail.module..
 */

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\Core\Link;
use Drupal\Core\Url;

/**
 * Implements hook_help().
 */
function demomail_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the demomail module.
    case 'help.page.demomail':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('How to send an email programmatically') . '</p>';
      return $output;

    default:
  }
}


/**
 * Implements hook_mail().
 */
function demomail_mail($key, &$message, $params) {
  $options = array(
    'langcode' => $message['langcode'],
  );

  switch ($key) {
    case 'create_article':
      $message['from'] = \Drupal::config('system.site')->get('mail');
      $message['subject'] = t('Article created: @title', array('@title' => $params['node_title']), $options);
      $message['body'][] = $params['message'];
      break;
  }
}

/**
 * Implements hook_entity_insert().
 */
function demomail_entity_insert(Drupal\Core\Entity\EntityInterface $entity) {

  if ($entity->getEntityTypeId() !== 'node' || ($entity->getEntityTypeId() === 'node' && $entity->bundle() !== 'article')) {
    return;
  }

  $mailManager = \Drupal::service('plugin.manager.mail');

  //send to all members in room 
  $members = $entity->get('field_add_guests')->getValue();
  $tos = [];
  foreach ( $members as $member ) {
      if ($member['target_id'] !== '0') {
          $tid = intval($member['target_id']);
          $user = \Drupal\user\Entity\User::load( $tid );
          $tos[] = $user->getEmail();
      }
  }

  $membersTo = implode (', ', $tos);

  $module = 'demomail';
  $key = 'create_article';
  $to = $membersTo;
  
  $params['message'] = 'http://localhost/fortesting/web/node/117';
  $params['node_title'] = $entity->label();
  $langcode = \Drupal::currentUser()->getPreferredLangcode();
  $send = true;

  $result = $mailManager->mail($module, $key, $to, $langcode, $params, NULL, $send);
  if ($result['result'] !== true) {
    drupal_set_message(t('There was a problem sending your message and it was not sent.'), 'error');
  }
  else {
    drupal_set_message(t('Your message has been sent.'));
  }

}