<?php

function rti_skeleton_preprocess_page(&$variables) {

  // Load the current user.
  $user = \Drupal\user\Entity\User::load(\Drupal::currentUser()->id());
  
  // get field data from that user
  //$variables['jobtitle'] = $user->get('field_job_title')->value;
  
  // some default getters include
  $email = $user->get('mail')->value;
  $name = $user->get('name')->value;
  $uid= $user->get('uid')->value;
  
  }
